{% set name = "urwid_readline" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/urwid_readline-{{ version }}.tar.gz
  sha256: 9301444b86d58f7d26388506b704f142cefd193888488b4070d3a0fdfcfc0f84

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - urwid

test:
  imports:
    - urwid_readline
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rr-/urwid_readline
  summary: A textbox edit widget for urwid that supports readline shortcuts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inducer
