{% set name = "urwid_readline" %}
{% set version = "0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urwid_readline-{{ version }}.tar.gz
  sha256: 8fabd2e501c124a30d38cfb10610b32f119a615ec0b310ae5591c583fb00bd09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - urwid

test:
  imports:
    - urwid_readline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rr-/urwid_readline
  summary: A textbox edit widget for urwid that supports readline shortcuts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inducer
